services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GPR_TOKEN: ${GPR_TOKEN}
    command: run --project WebApplication
    container_name: mobile-tracking-api
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - .:/app

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    restart: unless-stopped


volumes:
  postgres:

networks:
  mynetwork:
    driver: bridge
